#!/bin/sh

echo "Stoping Spring Boot Application..."
PID=$(echo $(lsof -n -i4TCP:8080) | awk 'NR==1{print $11}')
echo "Spring Boot Application PID=${PID}"
kill -9 $PID
echo "Spring Boot Application is stopped"
echo "----------------------------------"
echo "----------------------------------"

# shutdown logs of ED
PID=$(echo $(ps | grep -e "docker-compose logs --follow" | grep -v "grep")  | awk 'NR==1{print $1}')
echo "ElasticSearch logs PID=${PID}"
kill -9 $PID

# shutdown logs of Kibana
PID=$(echo $(ps | grep -e "docker-compose logs --follow" | grep -v "grep")  | awk 'NR==1{print $1}')
echo "Kibana logs PID=${PID}"
kill -9 $PID

echo "Stoping Kibana..."
docker stop kibana-container
echo "Kibana is stopped"
echo "Stoping ElasticSearch..."
docker stop elastic-container
echo "ElasticSearch is stopped"
